<a href="https://colab.research.google.com/github/santiagoIbarraM/Evaluaciones_python_aplicado_a_la_ingenieria/blob/main/Examen_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Evaluacion 3
Python aplicado a la ingenieria 202520

Docente: Miguel Angel Ortiz

Estudiante: Santiago Ibarra

Correo: Santiago.ibarra@upb.edu.co

Fecha: 10 de Septiembre del 2025


In [15]:
import numpy as np

data = np.genfromtxt('/GHI_Temp_Daily_Hourly_2024.csv', delimiter=';', skip_header=True)
print(data.shape)

print(f"Filas: {data.shape[0]}")
print(f"Columnas: {data.shape[1]}")

#El archivo tiene 8785 filas y 3 columnas
#Las filas representan datos de GHI y temperatura en tiempos determinados

year=2024
month= 1
day = 1

filtered_data= data[(data[:,0] == year) & (data[:,1] == month) & (data[:,2] == day)]
print(filtered_data)

print(f"Los datos corresponden al año: {year}, mes: {month}, día: {day}")
print(f"Registros encontrados: {len(filtered_data)}")

(8785, 6)
Filas: 8785
Columnas: 6
[[2.024e+03 1.000e+00 1.000e+00 0.000e+00 2.730e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+00 2.680e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 2.000e+00 2.640e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 3.000e+00 2.610e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 4.000e+00 2.590e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 5.000e+00 2.560e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 6.000e+00 2.540e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 7.000e+00 2.520e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 8.000e+00 2.510e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 9.000e+00 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+01 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.100e+01 2.550e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.200e+01 2.740e+01 8.000e+01]
 [2.024e+03 1.000e+00 1.000e+00 1.300e+01 2.940e+01 2.970e+02]
 [2.024e+03 1.000e+00 1.000e+00 1.400e+01 3.140e+01 4.680e+02]
 [2.024e+03 1.000e+00

In [16]:
def filter_data_by_date(filepath:str, year:int, month:int, day:int):
    try:
        data = np.genfromtxt(filepath, delimiter=';', skip_header=True)
        filtered_data = data[(data[:,0] == year) & (data[:,1] == month) & (data[:,2] == day)]
        if len(filtered_data) == 0:
            print(f"No se encontraron datos para la fecha: {year}-{month}-{day}")
            return
        filename = f"filtered_data_{year}_{month:02d}_{day:02d}.csv"
        with open(filename, 'w') as f:
            f.write("Year;Month;Day;Hour;Temperature;GHI\n")
            for row in filtered_data:
                f.write(f"{int(row[0])};{int(row[1])};{int(row[2])};{int(row[3])};{row[4]};{row[5]:.2f}\n")
        print("Datos filtrados guardados en:", filename)
        print(f"Se registraron {len(filtered_data)} registros.")
        temperature_mean = np.mean(filtered_data[:,4])
        temperature_max = np.max(filtered_data[:,4])
        ghi_mean = np.mean(filtered_data[:,5])
        ghi_max = np.max(filtered_data[:,5])
        print(f"Temperatura promedio: {temperature_mean:.2f} °C")
        print(f"Temperatura máxima: {temperature_max:.2f} °C")
        print(f"GHI promedio: {ghi_mean:.2f} W/m²")
        print(f"GHI máxima: {ghi_max:.2f} W/m²")

    except FileNotFoundError:
        print("El archivo no se encontró:", filepath)
    except IndexError:
        print("Error al procesar los datos. Verifique el formato del archivo.")
    except Exception as e:
        print("Ocurrió un error:", str(e))


filter_data_by_date('/GHI_Temp_Daily_Hourly_2024.csv', 2024, 1, 1)

Datos filtrados guardados en: filtered_data_2024_01_01.csv
Se registraron 24 registros.
Temperatura promedio: 28.79 °C
Temperatura máxima: 35.20 °C
GHI promedio: 185.54 W/m²
GHI máxima: 627.00 W/m²


In [17]:
if __name__ == "__main__":

    #filter_data_by_date('GHI_Temp_Daily_Hourly_2024.csv', 2024, 1, 1)
    #filter_data_by_date('GHI_Temp_Daily_Hourly_2024.csv', 2024, 2, 30)
    #filter_data_by_date('GHI_Temp_Daily_Hourly_2022.csv', 2022, 1, 1)
    #filter_data_by_date('GHI_Temp_Daily_Hourly_2024.csv', 2024, 1, 2)

    filter_data_by_date('/GHI_Temp_Daily_Hourly_2024.csv', 2024, 1, 1)
    ghi_temp_data = np.genfromtxt('filtered_data_2024_01_01.csv', delimiter=';', skip_header=True)
    print(ghi_temp_data)
    print(len(ghi_temp_data))

    hours = ghi_temp_data[:,3]
    temperature = ghi_temp_data[:,4]
    ghi = ghi_temp_data[:,5]
    print("Horas:", hours)
    print("Temperaturas (°C):", temperature)
    print("GHI (W/m²):", ghi)

    stc_temp = 25
    temp_coeff = -0.004
    panel_area = 1.65
    panel_efficiency = 0.2
    n_panels = 10
    total_area = panel_area * n_panels
    inverter_efficiency = 0.95

    temp_correction = 1 + temp_coeff * (ghi_temp_data[:,4] - stc_temp)
    dc_power = ghi_temp_data[:,5] * total_area * panel_efficiency * temp_correction
    ac_power = dc_power * inverter_efficiency
    print("Potencia AC generada (W):", ac_power)
    print("Potencia DC generada (W):", dc_power)

    hourly_energy_kwh = ac_power / 1000
    total_daily_energy_kwh = np.sum(hourly_energy_kwh)
    filename = f"energy_data_{year}_{month:02d}_{day:02d}.csv"

# Crear archivo CSV
with open(filename, "w") as datafile:
    datafile.write("Hour,Power_DC,Power_AC,Energy_kWh\n")
    # Escribir los registros
    for i in range(len(hours)):
        datafile.write(
            f"{hours[i]},{dc_power[i]:.2f},{ac_power[i]:.2f},{hourly_energy_kwh[i]:.2f}\n"
        )
    print(f"Archivo '{filename}' creado con {len(hours)} registros.")
    print(f"Potencia promedio DC: {np.mean(dc_power):.2f} W")
    print(f"Potencia promedio AC: {np.mean(ac_power):.2f} W")
    print(f"Energía total producida: {np.sum(hourly_energy_kwh):.2f} kWh")

Datos filtrados guardados en: filtered_data_2024_01_01.csv
Se registraron 24 registros.
Temperatura promedio: 28.79 °C
Temperatura máxima: 35.20 °C
GHI promedio: 185.54 W/m²
GHI máxima: 627.00 W/m²
[[2.024e+03 1.000e+00 1.000e+00 0.000e+00 2.730e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+00 2.680e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 2.000e+00 2.640e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 3.000e+00 2.610e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 4.000e+00 2.590e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 5.000e+00 2.560e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 6.000e+00 2.540e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 7.000e+00 2.520e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 8.000e+00 2.510e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 9.000e+00 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+01 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.100e+01 2.550e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.200e+01 2.74

In [18]:

def energy_calculations(filepath:str, year:int, month:int, day:int, n_panels:int,panel_area:float, panel_efficiency:float,
                        inverter_efficiency:float,stc_temp:float=25, temp_coeff:float=-0.004):

    filter_data_by_date(filepath, year, month, day)
    ghi_temp_data = np.genfromtxt('filtered_data_2024_01_01.csv', delimiter=';', skip_header=True)
    print(ghi_temp_data)
    print(len(ghi_temp_data))

    hours = ghi_temp_data[:,3]
    temperature = ghi_temp_data[:,4]
    ghi = ghi_temp_data[:,5]
    print("Horas:", hours)
    print("Temperaturas (°C):", temperature)
    print("GHI (W/m²):", ghi)

    temp_correction = 1 + temp_coeff * (ghi_temp_data[:,4] - stc_temp)
    dc_power = ghi_temp_data[:,5] * total_area * panel_efficiency * temp_correction
    ac_power = dc_power * inverter_efficiency
    print("Potencia AC generada (W):", ac_power)
    print("Potencia DC generada (W):", dc_power)

    hourly_energy_kwh = ac_power / 1000
    total_daily_energy_kwh = np.sum(hourly_energy_kwh)
    filename = f"energy_data_{year}_{month:02d}_{day:02d}.csv"

# Crear archivo CSV
with open(filename, "w") as datafile:
    datafile.write("Hour,Power_DC,Power_AC,Energy_kWh\n")
    # Escribir los registros
    for i in range(len(hours)):
        datafile.write(
            f"{hours[i]},{dc_power[i]:.2f},{ac_power[i]:.2f},{hourly_energy_kwh[i]:.2f}\n"
        )
    print(f"Archivo '{filename}' creado con {len(hours)} registros.")
    print(f"Potencia promedio DC: {np.mean(dc_power):.2f} W")
    print(f"Potencia promedio AC: {np.mean(ac_power):.2f} W")
    print(f"Energía total producida: {np.sum(hourly_energy_kwh):.2f} kWh")


energy_calculations('GHI_Temp_Daily_Hourly_2024.csv', 2024, 12, 11, 10, 1.65, 0.2, 0.95)

Archivo 'energy_data_2024_01_01.csv' creado con 24 registros.
Potencia promedio DC: 592.44 W
Potencia promedio AC: 562.82 W
Energía total producida: 13.51 kWh
El archivo no se encontró: GHI_Temp_Daily_Hourly_2024.csv
[[2.024e+03 1.000e+00 1.000e+00 0.000e+00 2.730e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+00 2.680e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 2.000e+00 2.640e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 3.000e+00 2.610e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 4.000e+00 2.590e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 5.000e+00 2.560e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 6.000e+00 2.540e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 7.000e+00 2.520e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 8.000e+00 2.510e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 9.000e+00 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.000e+01 2.490e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000e+00 1.100e+01 2.550e+01 0.000e+00]
 [2.024e+03 1.000e+00 1.000